### ISSUE TITLE
v2023.06.30 mysteriously appeared and pins jupyterlab<4

### ISSUE THREAD

**Issue by scottyhq** [conda-forge/pangeo-notebook-feedstock#159]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I noticed there is pangeo-notebook=2023.06.30 on conda-forge, but no corresponding tag in this repository.

https://github.com/conda-forge/pangeo-notebook-feedstock/blob/a1b2d4099a069c7476c89462586d0be99f3bdd5f/recipe/meta.yaml#L18

`mamba search pangeo-notebook --info`
```
pangeo-notebook 2023.06.28 hd8ed1ab_1
-------------------------------------
file name   : pangeo-notebook-2023.06.28-hd8ed1ab_1.conda
name        : pangeo-notebook
version     : 2023.06.28
build       : hd8ed1ab_1
build number: 1
size        : 6 KB
license     : MIT
subdir      : noarch
url         : https://conda.anaconda.org/conda-forge/noarch/pangeo-notebook-2023.06.28-hd8ed1ab_1.conda
md5         : 97506536af8d801d89c8fa7d9cb2d1cb
timestamp   : 2023-06-28 02:22:43 UTC
dependencies: 
  - dask-labextension 6.1.0.*
  - ipywidgets 8.0.6.*
  - jupyter-server-proxy 4.0.0.*
  - jupyterhub-singleuser 4.0.1.*
  - jupyterlab 4.0.2.*
  - nbgitpuller 1.1.1.*
  - pangeo-dask 2023.06.27.*


pangeo-notebook 2023.06.30 hd8ed1ab_1
-------------------------------------
file name   : pangeo-notebook-2023.06.30-hd8ed1ab_1.conda
name        : pangeo-notebook
version     : 2023.06.30
build       : hd8ed1ab_1
build number: 1
size        : 6 KB
license     : MIT
subdir      : noarch
url         : https://conda.anaconda.org/conda-forge/noarch/pangeo-notebook-2023.06.30-hd8ed1ab_1.conda
md5         : c20506502866448da91a957e1ecb4493
timestamp   : 2023-06-30 23:22:44 UTC
dependencies: 
  - dask-labextension 6.1.0.*
  - ipywidgets 8.0.6.*
  - jupyter-server-proxy 4.0.0.*
  - jupyterhub-singleuser 4.0.1.*
  - jupyterlab <4.0
  - nbgitpuller 1.1.1.*
  - pangeo-dask 2023.06.27.*
```

Can anyone help identify how that got there? cc @yuvipanda @ocefpaf

**Comment by ocefpaf** [comment]
I'm on mobile so it is hard to find things but it seems that the pangeo bot updated it, no?

**Comment by yuvipanda** [comment]
ugh, I was experimenting with this on the GitHub UI, and realized I should stop when it by default created a branch in the same repo than in my fork! I killed it before it made the PR, thinking that would prevent anything bad from happening :( I figured I'd come back to it after this weekend, but apparently just me editing and creating the branch made the package :( 

Sorry everyone!

**Comment by yuvipanda** [comment]
jupyterlab-git (https://github.com/jupyterlab/jupyterlab-git/issues/1245) and possibly other extensions no longer worked because of the 4.0 migration, which was my reason for poking at this.

**Comment by yuvipanda** [comment]
https://github.com/conda-forge/pangeo-notebook-feedstock/commit/0726a9e57f0d96e68cd910c22fd79200b2621d43 was the commit.

**Comment by scottyhq** [comment]
> apparently just me editing and creating the branch made the package

All good! I'm just glad to know that I'm not going crazy :)
