### ISSUE TITLE
Bump to Jupyterlab 2.0 

### ISSUE THREAD

**Issue by scottyhq** [conda-forge/pangeo-notebook-feedstock#21]
@jhamman and @TomAugspurger Jupyterlab 2 has been out for a while now, should we start using it? 

`jupyterlab                     2.1.2            py_0  conda-forge` 

we currently have:
https://github.com/conda-forge/pangeo-notebook-feedstock/blob/cd27474ad39ae22078c1bdaba72c664f5d294c32/recipe/meta.yaml#L18

- [ ] should we pin '>=2' or pin explicitly and make pangeo-bot bump versions when released? https://github.com/pangeo-bot/pangeo-notebook-feedstock/blob/master/.github/workflows/watch-conda-forge.yml#L106 

- [ ] maybe wait until repo2docker bumps to jlab>2.0 for binder consistency? https://github.com/jupyter/repo2docker/blob/26542dfc85c0a9567d2f266d51810c3a85244880/repo2docker/buildpacks/conda/environment.yml#L4 . see also https://github.com/jupyter/repo2docker/issues/724

**Comment by TomAugspurger** [comment]
Trying >=2 seems OK to me.

**Comment by jhamman** [comment]
The ML image requires the jupyterlay-nvdashboard package which is still not jlab 2 compatible: https://github.com/rapidsai/jupyterlab-nvdashboard/issues/51. 

Is there a feature in jlab 2 we're dying to have?

**Comment by scottyhq** [comment]
happy to wait

**Comment by scottyhq** [comment]
closed by #25
