### ISSUE TITLE
off-label github actions usage

### ISSUE THREAD

**Issue by beckermr** [conda-forge/pangeo-notebook-feedstock#49]
Hi @conda-forge/pangeo-notebook!

We noticed that you have been using GitHub actions to help trigger your own CIs and keep recipes up to date. While we don't currently have a specific policy against this, please be aware that

1. Feedstock rerendering relies on github actions. If every user in conda-forge does this it will easily cripple the organization as a whole.

2. We may at some future date have policies that impact the CI pipelines you have here, potentially banning them in order to preserve community resources.

I'd very much like you to these CI pipelines outside of conda-forge. They can easily be written there.

cc @conda-forge/core

**Comment by beckermr** [comment]
FYI, we are working on a draft policy around this here: https://github.com/conda-forge/conda-forge.github.io/pull/1199/files

**Comment by TomAugspurger** [comment]
> I'd very much like you to these CI pipelines outside of conda-forge. They can easily be written there.

We use the actions to trigger rebuilds when upstream packages change. Do you have any examples of actions triggering pull requests from a different organization / repository?

**Comment by beckermr** [comment]
You need to have your bot fork this repo, make its changes, and then make a PR and merge it. This can all be done via the github api and git. It needs to be done on CI services outside of conda-forge.

**Comment by scottyhq** [comment]
ok, we have:
* dispatch2pangeo-docker-images.yml
* sync-pangeobot-fork.yml 
* watch-conda-forge.yml

two of these workflows are configured to only run on the fork anyways (watch-conda-forge, sync-pangeobot), so I think we can just delete them in this repo.
https://github.com/conda-forge/pangeo-notebook-feedstock/blob/84c9a6b56e07e50cf14a172527d2a40b628ee28f/.github/workflows/watch-conda-forge.yml#L11 

i'm wondering if a cleaner config is to have a central `pangeo-bot/dispatcher` repo where all the watching happens. and then those workflows trigger creating branches and opening PRs in respective forks. (https://github.com/peter-evans/repository-dispatch)

I think that refactoring would also solve https://github.com/conda-forge/pangeo-dask-feedstock/issues/48

**Comment by beckermr** [comment]
Yup. A central feedstock in another repo is how we structure our bots.

**Comment by jhamman** [comment]
It might be interesting to discuss upstreaming the functionality in this repo (and the pangeo-dask-feedstock). What are we doing here? Well, we're using this feedstock to curate a metapackage with pinned package versions. The actions we run here do for metapackages what other the conda-forge bots do for regular feedstocks. Instead of watching Pypi for releases, we watch conda-forge for newly published versions of the packages included in the metapackage. In previous discussion with @ocefpaf, I seem to remember that some of this functionality may be useful to think about as part of conda-forge.

**Comment by beckermr** [comment]
Great idea! PRs to our bots repo (regro/cf-scripts) are more than welcome! 

Note that our own bots run outside of the conda-forge GitHub organization as well.

**Comment by scottyhq** [comment]
closed by #63
