### ISSUE TITLE
Jupyterlab 3

### ISSUE THREAD

**Issue by scottyhq** [conda-forge/pangeo-notebook-feedstock#52]
We currently pin Jlab>=2. Jupyterlab3 which includes new extensions (https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html)

see also:
https://www.quansight.com/post/why-we-are-excited-about-jupyterlab-3-0-dynamic-extensions 

so I believe our options are 1) pin to jlab=2 for now or 2) keep pin as is and wait for extensions to update before building new images
https://github.com/conda-forge/pangeo-notebook-feedstock/blob/ec9db37b304dd07a473e1a1d43b3d78967b510de/recipe/meta.yaml#L13-L20

@consideratio or @TomAugspurger is NodeJS used for other things? If we can drop it as a dependency that would be nice because it would reduce image size and we could remove these 'clean up' lines in Docker images

https://github.com/pangeo-data/pangeo-docker-images/blob/8cebf16a73bfd3f74a22353e176fa21eb7435c96/base-image/Dockerfile#L98-L99

**Comment by jhamman** [comment]
do we know if dask-labextension is working with jupyterlab 3? I would guess that is the most likely blocker.

**Comment by scottyhq** [comment]
> do we know if dask-labextension is working with jupyterlab 3? I would guess that is the most likely blocker.

Not quite. see: https://github.com/pangeo-data/pangeo-docker-images/pull/174

**Comment by TomAugspurger** [comment]
https://github.com/dask/dask-labextension/pull/162 for dask-labextension.

I think those cleanup lines are cleaning up files from Bokeh. Whether or not they can be removed depends on if bokeh is still shipping them.

IIRC nodejs is required to build jupyterlab 2.x extensions. I don't know if that's the case for 3.x extensions.

**Comment by ian-r-rose** [comment]
> IIRC nodejs is required to build jupyterlab 2.x extensions. I don't know if that's the case for 3.x extensions.

Yeah, this update involves a decent amount of churn in the packaging, but the payoff is that there should be no more need for nodejs or a lengthy-and-expensive build process for users. All assets should just be pip/conda installable.

**Comment by scottyhq** [comment]
glancing over at repo2docker, we will want to pay attention to https://github.com/jupyterhub/repo2docker/issues/956 as well. 

for now we are temporarily pinning jupyterlab=2, ipywidgets=7, dask-labextension=3 at major versions and not updating to new versions via CI (https://github.com/conda-forge/pangeo-notebook-feedstock/pull/54)

**Comment by scottyhq** [comment]
closed by #59
